// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.12.4
// source: association.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Mensagens de Requisição e Resposta
type AssociateDriverToVehicleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DriverId  int32 `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	VehicleId int32 `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
}

func (x *AssociateDriverToVehicleRequest) Reset() {
	*x = AssociateDriverToVehicleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_association_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssociateDriverToVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateDriverToVehicleRequest) ProtoMessage() {}

func (x *AssociateDriverToVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_association_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateDriverToVehicleRequest.ProtoReflect.Descriptor instead.
func (*AssociateDriverToVehicleRequest) Descriptor() ([]byte, []int) {
	return file_association_proto_rawDescGZIP(), []int{0}
}

func (x *AssociateDriverToVehicleRequest) GetDriverId() int32 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *AssociateDriverToVehicleRequest) GetVehicleId() int32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

type AssociateDriverToVehicleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AssociateDriverToVehicleResponse) Reset() {
	*x = AssociateDriverToVehicleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_association_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssociateDriverToVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateDriverToVehicleResponse) ProtoMessage() {}

func (x *AssociateDriverToVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_association_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateDriverToVehicleResponse.ProtoReflect.Descriptor instead.
func (*AssociateDriverToVehicleResponse) Descriptor() ([]byte, []int) {
	return file_association_proto_rawDescGZIP(), []int{1}
}

type GetAllAssociationsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllAssociationsRequest) Reset() {
	*x = GetAllAssociationsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_association_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllAssociationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAssociationsRequest) ProtoMessage() {}

func (x *GetAllAssociationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_association_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAssociationsRequest.ProtoReflect.Descriptor instead.
func (*GetAllAssociationsRequest) Descriptor() ([]byte, []int) {
	return file_association_proto_rawDescGZIP(), []int{2}
}

type GetAllAssociationsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Associations []*Association `protobuf:"bytes,1,rep,name=associations,proto3" json:"associations,omitempty"`
}

func (x *GetAllAssociationsResponse) Reset() {
	*x = GetAllAssociationsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_association_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllAssociationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAssociationsResponse) ProtoMessage() {}

func (x *GetAllAssociationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_association_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAssociationsResponse.ProtoReflect.Descriptor instead.
func (*GetAllAssociationsResponse) Descriptor() ([]byte, []int) {
	return file_association_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllAssociationsResponse) GetAssociations() []*Association {
	if x != nil {
		return x.Associations
	}
	return nil
}

type GetDriversByVehicleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VehicleId int32 `protobuf:"varint,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
}

func (x *GetDriversByVehicleRequest) Reset() {
	*x = GetDriversByVehicleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_association_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDriversByVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversByVehicleRequest) ProtoMessage() {}

func (x *GetDriversByVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_association_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversByVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetDriversByVehicleRequest) Descriptor() ([]byte, []int) {
	return file_association_proto_rawDescGZIP(), []int{4}
}

func (x *GetDriversByVehicleRequest) GetVehicleId() int32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

type GetDriversByVehicleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DriverIds []int32 `protobuf:"varint,1,rep,packed,name=driver_ids,json=driverIds,proto3" json:"driver_ids,omitempty"`
}

func (x *GetDriversByVehicleResponse) Reset() {
	*x = GetDriversByVehicleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_association_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDriversByVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversByVehicleResponse) ProtoMessage() {}

func (x *GetDriversByVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_association_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversByVehicleResponse.ProtoReflect.Descriptor instead.
func (*GetDriversByVehicleResponse) Descriptor() ([]byte, []int) {
	return file_association_proto_rawDescGZIP(), []int{5}
}

func (x *GetDriversByVehicleResponse) GetDriverIds() []int32 {
	if x != nil {
		return x.DriverIds
	}
	return nil
}

type GetVehiclesByDriverRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DriverId int32 `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
}

func (x *GetVehiclesByDriverRequest) Reset() {
	*x = GetVehiclesByDriverRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_association_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVehiclesByDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehiclesByDriverRequest) ProtoMessage() {}

func (x *GetVehiclesByDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_association_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehiclesByDriverRequest.ProtoReflect.Descriptor instead.
func (*GetVehiclesByDriverRequest) Descriptor() ([]byte, []int) {
	return file_association_proto_rawDescGZIP(), []int{6}
}

func (x *GetVehiclesByDriverRequest) GetDriverId() int32 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

type GetVehiclesByDriverResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	VehicleIds []int32 `protobuf:"varint,1,rep,packed,name=vehicle_ids,json=vehicleIds,proto3" json:"vehicle_ids,omitempty"`
}

func (x *GetVehiclesByDriverResponse) Reset() {
	*x = GetVehiclesByDriverResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_association_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetVehiclesByDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehiclesByDriverResponse) ProtoMessage() {}

func (x *GetVehiclesByDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_association_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehiclesByDriverResponse.ProtoReflect.Descriptor instead.
func (*GetVehiclesByDriverResponse) Descriptor() ([]byte, []int) {
	return file_association_proto_rawDescGZIP(), []int{7}
}

func (x *GetVehiclesByDriverResponse) GetVehicleIds() []int32 {
	if x != nil {
		return x.VehicleIds
	}
	return nil
}

type DissociateDriverFromVehicleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DriverId  int32 `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	VehicleId int32 `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
}

func (x *DissociateDriverFromVehicleRequest) Reset() {
	*x = DissociateDriverFromVehicleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_association_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DissociateDriverFromVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DissociateDriverFromVehicleRequest) ProtoMessage() {}

func (x *DissociateDriverFromVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_association_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DissociateDriverFromVehicleRequest.ProtoReflect.Descriptor instead.
func (*DissociateDriverFromVehicleRequest) Descriptor() ([]byte, []int) {
	return file_association_proto_rawDescGZIP(), []int{8}
}

func (x *DissociateDriverFromVehicleRequest) GetDriverId() int32 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DissociateDriverFromVehicleRequest) GetVehicleId() int32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

type DissociateDriverFromVehicleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DissociateDriverFromVehicleResponse) Reset() {
	*x = DissociateDriverFromVehicleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_association_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DissociateDriverFromVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DissociateDriverFromVehicleResponse) ProtoMessage() {}

func (x *DissociateDriverFromVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_association_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DissociateDriverFromVehicleResponse.ProtoReflect.Descriptor instead.
func (*DissociateDriverFromVehicleResponse) Descriptor() ([]byte, []int) {
	return file_association_proto_rawDescGZIP(), []int{9}
}

type Association struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DriverId  int32 `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	VehicleId int32 `protobuf:"varint,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
}

func (x *Association) Reset() {
	*x = Association{}
	if protoimpl.UnsafeEnabled {
		mi := &file_association_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Association) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Association) ProtoMessage() {}

func (x *Association) ProtoReflect() protoreflect.Message {
	mi := &file_association_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Association.ProtoReflect.Descriptor instead.
func (*Association) Descriptor() ([]byte, []int) {
	return file_association_proto_rawDescGZIP(), []int{10}
}

func (x *Association) GetDriverId() int32 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *Association) GetVehicleId() int32 {
	if x != nil {
		return x.VehicleId
	}
	return 0
}

var File_association_proto protoreflect.FileDescriptor

var file_association_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5d, 0x0a, 0x1f, 0x41, 0x73,
	0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x56,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09,
	0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x20, 0x41, 0x73, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x56, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1b, 0x0a,
	0x19, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x54, 0x0a, 0x1a, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0c, 0x61, 0x73, 0x73, 0x6f,
	0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0c, 0x61, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x22, 0x3b, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x42, 0x79,
	0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x3c, 0x0a,
	0x1b, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x42, 0x79, 0x56, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05,
	0x52, 0x09, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x73, 0x22, 0x39, 0x0a, 0x1a, 0x47,
	0x65, 0x74, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x72, 0x69,
	0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x56, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x05, 0x52, 0x0a, 0x76, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x49, 0x64, 0x73, 0x22, 0x60, 0x0a, 0x22, 0x44, 0x69, 0x73, 0x73, 0x6f, 0x63,
	0x69, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x56, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x25, 0x0a, 0x23, 0x44, 0x69, 0x73, 0x73,
	0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d,
	0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x49, 0x0a, 0x0b, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b,
	0x0a, 0x09, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x64, 0x72, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x76,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x09, 0x76, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x32, 0x8e, 0x04, 0x0a, 0x12, 0x41,
	0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x6b, 0x0a, 0x18, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x44, 0x72,
	0x69, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x12, 0x26, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x73,
	0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x54, 0x6f, 0x56,
	0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x13, 0x47, 0x65, 0x74,
	0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x42, 0x79, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65,
	0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x72, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x42, 0x79, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x44,
	0x72, 0x69, 0x76, 0x65, 0x72, 0x73, 0x42, 0x79, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5c, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x56, 0x65,
	0x68, 0x69, 0x63, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x21,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c,
	0x65, 0x73, 0x42, 0x79, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x56, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x73, 0x42, 0x79, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x74, 0x0a, 0x1b, 0x44, 0x69, 0x73, 0x73, 0x6f, 0x63, 0x69,
	0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x56, 0x65, 0x68,
	0x69, 0x63, 0x6c, 0x65, 0x12, 0x29, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x73,
	0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x46, 0x72, 0x6f,
	0x6d, 0x56, 0x65, 0x68, 0x69, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x73, 0x73, 0x6f, 0x63, 0x69, 0x61,
	0x74, 0x65, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x46, 0x72, 0x6f, 0x6d, 0x56, 0x65, 0x68, 0x69,
	0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x66,
	0x6c, 0x65, 0x65, 0x74, 0x5f, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_association_proto_rawDescOnce sync.Once
	file_association_proto_rawDescData = file_association_proto_rawDesc
)

func file_association_proto_rawDescGZIP() []byte {
	file_association_proto_rawDescOnce.Do(func() {
		file_association_proto_rawDescData = protoimpl.X.CompressGZIP(file_association_proto_rawDescData)
	})
	return file_association_proto_rawDescData
}

var file_association_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_association_proto_goTypes = []any{
	(*AssociateDriverToVehicleRequest)(nil),     // 0: proto.AssociateDriverToVehicleRequest
	(*AssociateDriverToVehicleResponse)(nil),    // 1: proto.AssociateDriverToVehicleResponse
	(*GetAllAssociationsRequest)(nil),           // 2: proto.GetAllAssociationsRequest
	(*GetAllAssociationsResponse)(nil),          // 3: proto.GetAllAssociationsResponse
	(*GetDriversByVehicleRequest)(nil),          // 4: proto.GetDriversByVehicleRequest
	(*GetDriversByVehicleResponse)(nil),         // 5: proto.GetDriversByVehicleResponse
	(*GetVehiclesByDriverRequest)(nil),          // 6: proto.GetVehiclesByDriverRequest
	(*GetVehiclesByDriverResponse)(nil),         // 7: proto.GetVehiclesByDriverResponse
	(*DissociateDriverFromVehicleRequest)(nil),  // 8: proto.DissociateDriverFromVehicleRequest
	(*DissociateDriverFromVehicleResponse)(nil), // 9: proto.DissociateDriverFromVehicleResponse
	(*Association)(nil),                         // 10: proto.Association
}
var file_association_proto_depIdxs = []int32{
	10, // 0: proto.GetAllAssociationsResponse.associations:type_name -> proto.Association
	0,  // 1: proto.AssociationService.AssociateDriverToVehicle:input_type -> proto.AssociateDriverToVehicleRequest
	2,  // 2: proto.AssociationService.GetAllAssociations:input_type -> proto.GetAllAssociationsRequest
	4,  // 3: proto.AssociationService.GetDriversByVehicle:input_type -> proto.GetDriversByVehicleRequest
	6,  // 4: proto.AssociationService.GetVehiclesByDriver:input_type -> proto.GetVehiclesByDriverRequest
	8,  // 5: proto.AssociationService.DissociateDriverFromVehicle:input_type -> proto.DissociateDriverFromVehicleRequest
	1,  // 6: proto.AssociationService.AssociateDriverToVehicle:output_type -> proto.AssociateDriverToVehicleResponse
	3,  // 7: proto.AssociationService.GetAllAssociations:output_type -> proto.GetAllAssociationsResponse
	5,  // 8: proto.AssociationService.GetDriversByVehicle:output_type -> proto.GetDriversByVehicleResponse
	7,  // 9: proto.AssociationService.GetVehiclesByDriver:output_type -> proto.GetVehiclesByDriverResponse
	9,  // 10: proto.AssociationService.DissociateDriverFromVehicle:output_type -> proto.DissociateDriverFromVehicleResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_association_proto_init() }
func file_association_proto_init() {
	if File_association_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_association_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AssociateDriverToVehicleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_association_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*AssociateDriverToVehicleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_association_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllAssociationsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_association_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetAllAssociationsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_association_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetDriversByVehicleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_association_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*GetDriversByVehicleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_association_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetVehiclesByDriverRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_association_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetVehiclesByDriverResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_association_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*DissociateDriverFromVehicleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_association_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*DissociateDriverFromVehicleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_association_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Association); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_association_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_association_proto_goTypes,
		DependencyIndexes: file_association_proto_depIdxs,
		MessageInfos:      file_association_proto_msgTypes,
	}.Build()
	File_association_proto = out.File
	file_association_proto_rawDesc = nil
	file_association_proto_goTypes = nil
	file_association_proto_depIdxs = nil
}
